// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfMPfKh4Vua_i9qwIAS13PwPUqXo2NSI',
    appId: '1:725547003537:web:934262a68bd16fd45a5930',
    messagingSenderId: '725547003537',
    projectId: 'safe-mate-467f6',
    authDomain: 'safe-mate-467f6.firebaseapp.com',
    storageBucket: 'safe-mate-467f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ZmpJaft_nF_nTnhuDhxk8NYGSFi821g',
    appId: '1:725547003537:android:0ab1ed36161ad8cf5a5930',
    messagingSenderId: '725547003537',
    projectId: 'safe-mate-467f6',
    storageBucket: 'safe-mate-467f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDofVBiGe_bxopYWFlU6F_uR6pZkAp0rAY',
    appId: '1:725547003537:ios:857ffaeaf5cf106c5a5930',
    messagingSenderId: '725547003537',
    projectId: 'safe-mate-467f6',
    storageBucket: 'safe-mate-467f6.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDofVBiGe_bxopYWFlU6F_uR6pZkAp0rAY',
    appId: '1:725547003537:ios:857ffaeaf5cf106c5a5930',
    messagingSenderId: '725547003537',
    projectId: 'safe-mate-467f6',
    storageBucket: 'safe-mate-467f6.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfMPfKh4Vua_i9qwIAS13PwPUqXo2NSI',
    appId: '1:725547003537:web:639ea3b9c28cbd705a5930',
    messagingSenderId: '725547003537',
    projectId: 'safe-mate-467f6',
    authDomain: 'safe-mate-467f6.firebaseapp.com',
    storageBucket: 'safe-mate-467f6.firebasestorage.app',
  );

}