// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqPV7TNUiOKI5R1ejqQ4ZiwNw1qSF7kU',
    appId: '1:474047722611:web:2c0a1ed9728b434039e606',
    messagingSenderId: '474047722611',
    projectId: 'general-firebase-affd9',
    authDomain: 'general-firebase-affd9.firebaseapp.com',
    storageBucket: 'general-firebase-affd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJnwdyb0T6bdFYL1eASJZgnsar-K6a9jM',
    appId: '1:474047722611:android:0ce42dd0aef468a439e606',
    messagingSenderId: '474047722611',
    projectId: 'general-firebase-affd9',
    storageBucket: 'general-firebase-affd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbt3P6u1SUxOxEPk63E4pk6lVDvoAyFDM',
    appId: '1:474047722611:ios:1d7c209ac2dd860b39e606',
    messagingSenderId: '474047722611',
    projectId: 'general-firebase-affd9',
    storageBucket: 'general-firebase-affd9.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbt3P6u1SUxOxEPk63E4pk6lVDvoAyFDM',
    appId: '1:474047722611:ios:1d7c209ac2dd860b39e606',
    messagingSenderId: '474047722611',
    projectId: 'general-firebase-affd9',
    storageBucket: 'general-firebase-affd9.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fYAbGOM34AFJZEbIwsGDuQhKvbvX_Xw',
    appId: '1:474047722611:web:28325523cf4c464339e606',
    messagingSenderId: '474047722611',
    projectId: 'general-firebase-affd9',
    authDomain: 'general-firebase-affd9.firebaseapp.com',
    storageBucket: 'general-firebase-affd9.firebasestorage.app',
  );
}